### ISSUE TITLE
Cannot create local-server using webpack-dev-server on ex.7

### ISSUE THREAD

**Issue by JerinJ** [hegdeashwin/learning-webpack#33]
If we try to run `webpack-dev-server` it throws un-recognizable error and it seems we dont have express integrated even here. Please correct if am wrong

![image](https://cloud.githubusercontent.com/assets/2240674/21388158/0ff49e16-c7a1-11e6-967f-444c79ad3d9d.png)

**Comment by hegdeashwin** [comment]
@JerinJ :+1:  Can you please try to install webpack and webpack-dev-server at global level. Express is internally used with in webpack-dev-server. Installing via below command would work.

```
npm install -g webpack webpack-dev-server
```
and than try running the example

**Comment by hegdeashwin** [comment]
I think, the installation step was missing, so added it on README.md

**Comment by JerinJ** [comment]
This worked.  :+1:

**Comment by hegdeashwin** [comment]
Thank you for noting this.
